import { Inter } from "next/font/google";
import "./globals.css";
import { LayoutDirectionProvider } from "./LayoutDirectionContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <LayoutDirectionProvider>
      <html lang="en" id="root-html">
        <body className={inter.className}>{children}</body>
      </html>
    </LayoutDirectionProvider>
  );
}
